---
- hosts: all
  become: yes

  tasks:
    - name: Update Packages
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"  ## condition 
    
- hosts: dev
  become: true
  
  tasks: 
     - name: Install apache in Ubuntu Server
       apt:
         name: apache2
         state: latest
       when: ansible_distribution == "Ubuntu"

