---
- hosts: all
  become: yes

  tasks:
    - name: Update Packages
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"  ## condition 

- hosts: dev
  become: yes
  roles:
     - dev

- hosts: workstation
  become: yes
  roles:
     - workstation



