
- name: Install apache in Ubuntu Server
  tags: apache
  apt:
    name:
      - "{{ apache_package_name }}"
    state: latest
  when: ansible_distribution == "Ubuntu"
- name: Ansible service
  tags: apache
  service:
     name: "{{ apache_service }}"
     state: started
     enabled: yes
- name:  copy default file html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: generate sshd_congif file from template 
  tags: ssh
  template:
     src: "{{ssh_template_file}}"
     dest: /etc/ssh/sshd_config
     owner: root
     group: root
     mode: 0644
  notify: restart_sshd
  
